import RecordJSON from '../../../interfaces/RecordJSON';
const AE: RecordJSON[] = [
  require('./10.json'),
  require('./11.json'),
  require('./20.json'),
  require('./21.json'),
  require('./22.json'),
  require('./23.json'),
  require('./30.json'),
  require('./31.json'),
  require('./32.json'),
  require('./33.json'),
  require('./34.json'),
  require('./35.json'),
  require('./36.json'),
  require('./40.json'),
  require('./41.json'),
  require('./47.json'),
  require('./50.json'),
  require('./52.json'),
  require('./60.json'),
  require('./62.json'),
  require('./89.json'),
  require('./90.json'),
  require('./SE13.json'),
  require('./SE16.json'),
  require('./SE17.json'),
  require('./SE20.json'),
  require('./SE30.json'),
  require('./SE35.json'),
  require('./SE36.json'),
  require('./SE50.json'),
];

export default AE;
